name: example
description: Example app for the ckb_flutter_client package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  ckb_flutter_client:
    path: ../
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
